### ISSUE TITLE
Buy review doesnot throw the exception when the user doesnot have enough balance 

### ISSUE THREAD

**Issue by DeepakSingh260** [InternKaro/STOCKS-DEKHO-API#35]
this [pull ](https://github.com/InternKaro/STOCKS-DEKHO-API/pull/34) will fix it .

**Comment by DeepakSingh260** [comment]
The Check order amount was an async function which was the reason for abnormal behavior.

**Comment by Parth0105** [comment]
Thanks @DeepakSingh260 do resolve changes suggested in next pr

**Comment by DeepakSingh260** [comment]
Sure thing
