### ISSUE TITLE
Add support for nodemon.

### ISSUE THREAD

**Issue by Parth0105** [InternKaro/STOCKS-DEKHO-API#6]

**Comment by DeepakSingh260** [comment]
Please Elaborate

**Comment by Parth0105** [comment]
We want to add support for nodemon in our project as we do not want to restart our server every time we want it to restart automatically after any code change.

**Comment by DeepakSingh260** [comment]
review my pull request https://github.com/InternKaro/STOCKS-DEKHO-API/pull/9

**Comment by Parth0105** [comment]
Thanks @DeepakSingh260 for contributing.
